name: MineCrawl
main: fr.co.MineCrawl
authors: [ Galyfray,SimonLefebvre ]
version: 0.1
api-version: 1.18
commands:
  balance:
    description: Allows you to get/set the balance of a player
    usage: /<command> get|set <player> <amount>
    permission: minecrawl.balance

  killmap:
    description: allow to set/get the amount earned by a player when killing an entity
    usage: /<command> get|set <entity> <amount>
    permission: minecrawl.killmap

